"""added active, expiry_date columns to user

Revision ID: e9c57613d88b
Revises: aa4d4c6374f2
Create Date: 2022-10-06 16:03:26.196457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c57613d88b'
down_revision = 'aa4d4c6374f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('expiry_date', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expiry_date')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
